### ISSUE TITLE
Images are incorrectly encoded after Azure Functions Deployment

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#100]
When deploying a Nitro app with the `azure-functions` preset, static Images such as .pngs and .jpgs are rendered incorrectly. (They are converted to string, which messes with their encoding.)

Issues to check:
* is this a limitation of azure functions? (not serving binary files)
* could this be resolved with something similar to https://github.com/unjs/nitro/issues/96?

context: https://github.com/nuxt/nuxt.js/issues/12677

**Comment by mcremer-able** [comment]
Got this ever resolved, because I have the same issues with fonts aswell.
In the generated function code we have 

```js
async function handle(context, req) {
  const url = "/" + (req.params.url || "");
  const { body, status, statusText, headers } = await nitroApp.localCall({
    url,
    headers: req.headers,
    method: req.method,
    body: req.rawBody
  });
  context.res = {
    status,
    headers,
    body: body ? body.toString() : statusText
  };
}
```
for static assets we use `readFile` wich returns a buffer, but the buffer.toString method sometime returns larger Object wich causes issues.

```js
promises.readFile("./font.woff").then((e) => {
  const ogLen = e.length;
  const stringLen = e.toString().length;
  console.log({ ogLen, stringLen });
});
// { ogLen: 561776, stringLen: 532428 }

```

If I change it to ` body: body ? body : statusText, `  it seems to work.
Would a pr with that change resolve this ?

**Comment by markgibbons25** [comment]
@danielroe hey mate any update on this one?

**Comment by edwh** [comment]
@markgibbons25 I tried this using `patch-package` and @mcremer-able's suggestion, which does the trick for me.  

The patch file is at https://github.com/Freegle/iznik-nuxt3/blob/master/patches/nitropack%2B2.1.0.patch

This issue was a godsend, as I was struggling to track down the problem, but loading an SVG successfully confirmed it was this one.
