### ISSUE TITLE
JSON proxy pretty prints response

### ISSUE THREAD

**Issue by Aareksio** [unjs/nitro#1605]
### Environment

Debian GNU/Linux 11 (bullseye)
node v20.4.0
nitropack 2.5.2

### Reproduction

https://github.com/Aareksio/reproduction-nitro-proxy-json

1. `pnpm install`
2. `pnpm dev`
3. Visit `/api/json` (eg. http://localhost:3000/api/json)
4. Visit `/api/proxied` (eg. http://localhost:3000/api/proxied)

### Describe the bug

Nitro pretty-prints the JSON response. This can greatly inflate bytes transferred over the wire if there is no compression applied to the response. Nitro should not intervene in the response unprompted.

### Expected result

Both responses are the same

```json
{"hello":"world"}
```

### Observed result

Proxied response is pretty-printed

```json
{
  "hello": "world"
}
```

### Additional context

It doesn't seem to be caused by h3

**Comment by pi0** [comment]
Thanks for making an issue with reproduction. 

I also made a [stackblitz clone](https://stackblitz.com/edit/github-szyz9z?file=nitro.config.ts,node_modules%2Fh3%2Fdist%2Findex.mjs,api%2Fjson.ts) with production build by default.

Pretty printing of JSON responses, only happens in **development mode** for easier debugging. When you run nitro/nuxt application in production, nitro configures h3 with the debugger disabled which also makes JSON responses not to be pretty printed. So this is not a bug but a feature that is only for development and nothing to worry about production of extra bytes.

----

BTW this is an interesting edge case since you are forced to use string and response still gets pretty printed. This behavior only happens with nitro proxies to the local URLs as we leverage a direct fetching system [h3 directly returns consumed `_data`](https://github.com/unjs/h3/blob/8af047416cf1e7c03d8a8ccc2cce137d4af50996/src/utils/proxy.ts#L133) which is a parsed value already available from [ofetch's `_data`](https://github.com/unjs/ofetch/blob/19b79fa5cbf24cda0a81bf768c636e01eef82541/src/fetch.ts#L207) getter as niro route rules for proxy, passes [direct `$fetch.raw`](https://github.com/unjs/nitro/blob/d5847816275c5f74efef74c2395789f1fd342322/src/runtime/route-rules.ts#L50).

**Comment by Aareksio** [comment]
Thanks, I did not think to test production build!
