### ISSUE TITLE
Undefined cache headers

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#1850]
Moved from https://github.com/nuxt/nuxt/issues/23877

Nitro: 2.7.0

Reproduction: https://stackblitz.com/edit/unjs-nitro-s7ircy

Response headers:

```
Etag: undefined
Last-Modified: undefined
```

**Comment by Tristan971** [comment]
This causes some fairly painful cache issues, where browsers will keep using stale document HTML, and break across updates.

Here is a workaround that will do the job with some drawbacks:

`server/plugins/cache-headers.ts for nuxt projects`
```ts
// replace with a value that is specific to your application's
// specific build; in our case `git-$YYYMMddHHmm-$commitSha`
const buildVersion = "changeme"; // useRuntimeConfig().public.version for example
const etag = `W/"${buildVersion}"`;

/**
 * Ensure Nitro always thinks it's a new request; and give up on 304s from it
 * which is fine since Varnish can do those for us just fine
 * (Workaround for https://github.com/unjs/nitro/issues/1850)
 */
export default defineNitroPlugin((nitroApp) => {
  // avoid nitro considering cache headers coming to it
  nitroApp.hooks.hook("request", (event) => {
    delete event.node.req.headers["if-modified-since"];
    delete event.node.req.headers["if-match"];
    delete event.node.req.headers["if-none-match"];
  });

  // remove Last-Modified's undefined + add build-specific ETag
  nitroApp.hooks.hook("beforeResponse", (event, _) => {
    event.node.res.removeHeader("Last-Modified");
    event.node.res.setHeader("ETag", etag);
  });
});
```

This setup will make nitro already return 200s instead of 304s. So if you don't have something above Nitro doing caching + ETag handling (like CF, Varnish, ...) then it will cause a lot more traffic for you and your users.

But if like us you do have some caching layer above it, it's relatively harmless afaict.

**Comment by pi0** [comment]
Sorry for inconnicnes, this will be fixed in nightly release and a hotfix release soon. I suggest to switch to nightly in the meantime (https://nitro.unjs.io/guide/getting-started#nightly-release-channel)

**Comment by ManasMadrecha** [comment]
@pi0 I tried with the nightly release, the issue is still present.

![image](https://github.com/unjs/nitro/assets/65993481/654bedf7-52bf-4280-8b08-99f3a30277db)

![image](https://github.com/unjs/nitro/assets/65993481/61b7fead-5b54-45c1-b686-3a50f6950f24)

**Comment by pi0** [comment]
@ManasMadrecha any chance you can share a reproduction? (also double check, if not using a cached response somehow from past)

**Comment by ManasMadrecha** [comment]
Sorry, but I can't share a reproduction project as it has confidential data. Kindly refer to my above edited comment with newer images.

In development, I deleted the cache folder inside the .nuxt folder, and then tested, still `undefined` error is there. Also, on production site, I disabled the cache in Browser console's Network tab, and still the new 200 fetch request had the undefined error. This has caused my production site to break because it is unable to fetch newer API content since Monday. I tried redeploying at 2.7.1-nightly and even on 2.7.0, still the error is there. 

Somehow the cache is simply not getting invalidated. Was some change made after 2.6.3 with regards to cache invalidation? Because last week, my app was properly fetching newer content.

**Comment by pi0** [comment]
There had been several cache related bug fixes in the last release (see https://github.com/unjs/nitro/releases/tag/v2.7.0)

Sadly i think there is a chance that production caches are leaked with `undefined` values that you still see it.

I will try to investigate and deploy another patch to mitigate this issue, in the meantime you can contact me in discord (pi0) if need to share any private info that helps on debugging.

**Comment by ManasMadrecha** [comment]
@pi0 

![image](https://github.com/unjs/nitro/assets/65993481/d482d560-e13f-498c-ad12-c8d4b9a6c0f5)

### In development 

with `.nuxt/cache` folder deleted and Browser's Network tool cache disabled:

![image](https://github.com/unjs/nitro/assets/65993481/6b4ac450-2d01-45d5-8734-e34012597a7b)

After this request, this is the generated cache file in the `.nuxt/cache` folder

```json
{
  "expires": 1698359968650,
  "value": {
    "code": 200,
    "headers": {
      "etag": "undefined",
      "last-modified": "undefined",
      "cache-control": "s-maxage=300, stale-while-revalidate"
    },
    "body": {
      "asOn": "2023-10-27T04:04:28+05:30",
      "quotes": [
        {
          "asOn": "2023-10-27T04:04:28+05:30",
          "docId": "b4n4ps",
          "dateDoc": "2023-10-26T15:29:49+05:30"
        }
      ]
    }
  },
  "mtime": 1698359668893,
  "integrity": "a6P148fJbX"
}
```

So, while `expires` and `mtime` are calculated properly, but `headers.etag` and `headers['last-modified']` are still undefined. Note: in they undefined in dev itself, so maybe issue is not with respect to production leak.

### In production

Still, the error is there.

![image](https://github.com/unjs/nitro/assets/65993481/ae8befe5-39a4-4990-95da-2acab7e98d0e)

----

Note: previously I had tried using @Tristan971 's plugin and my app works properly, but of course there will be more cost due to no cache (until I add cloudfare or something)

**Comment by ManasMadrecha** [comment]
@pi0 Can it be so that the following might be happening in this code?

https://github.com/unjs/nitro/blob/2d803a3cfbf274e7419605a8fb1e507fde5e8877/src/runtime/cache.ts#L357C34-L361C8

```
String(headers["Last-Modified"] || headers["last-modified"]  || new Date().toUTCString())
```

is being converted to

```
String("undefined" || headers["last-modified"]  || new Date().toUTCString())
```

So, the answer is coming as undefined?

**Comment by ManasMadrecha** [comment]
Will changing that code to this work?

```ts
// Manas

headers.etag = String(headers.Etag || headers.etag)
if (headers.etag === 'undefined' || headers.etag === undefined) headers.etag = `W/"${hash(body)}"`
      
headers['last-modified'] = String(headers['Last-Modified'] || headers['last-modified'])
if (headers['last-modified'] === 'undefined' || headers['last-modified'] === undefined) headers['last-modified'] = new Date().toUTCString()
```

**Comment by pi0** [comment]
We can have latest suggestion also but first i need to reproduce a situation when values are undefined (nullish). Kindly can you please either share more context of your project in dm? I would be more than happy to help working on any patch asap.

**Comment by Tristan971** [comment]
for what it's worth, I can still reproduce the issue on our end as well, with Nuxt 3.8.0 and Nitro 2.7.1

```
$ curl -I -XGET localhost:3000
HTTP/1.1 200 OK
Via: 1.1 mangadex-frontend
last-modified: undefined
etag: undefined
cache-control: s-maxage=30, stale-while-revalidate
content-type: text/html;charset=utf-8
x-powered-by: Nuxt
Date: Fri, 27 Oct 2023 06:16:13 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 3523
```

That is on a fresh cache (deleted `.nuxt` then build+preview), with just about everything default. The relevant route rule here is `"/": { swr: 30 },`.

Can't give a stackblitz example right now, but since we don't configure Nitro explicitly in any particular way (we have 2 plugins, 1 to add logging, and 1 which appends a bit of HTML), it should be very reproducible.

<details>
<summary>log plugin</summary>

```ts
import { IncomingMessage, ServerResponse } from "http";

export default defineEventHandler((event) => {
  const req: IncomingMessage = event.node.req;
  const reqHdr = req.headers;
  const reqRuid = reqHdr["x-request-id"] ?? "-";
  const reqSrc = reqHdr["x-forwarded-for"] ?? req.socket.remoteAddress;

  const res: ServerResponse = event.node.res;
  res.setHeader("Via", `${req.httpVersion} mangadex-frontend`);

  res.on("finish", () => {
    console.log(
      `${reqRuid} - ${reqSrc} - "${req.method} ${req.url}" ${res.statusCode}`
    );
  });
});
```

</details>

<details>
<summary>html appending</summary>

```ts
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook("render:html", (html, _: any) => {
    html.head.push(`<!--esi
<esi:comment text="ESI rendered" />
<esi:include src="ESI_OPENGRAPH" onerror="continue" />
-->`);
    html.body.push(`
<noscript>
    <div style="display: flex; justify-content: center; align-items: center; flex-direction: column; height: 100%; gap: 2rem;">
      <img
        src="/img/cat-books.svg"
        alt="Cat napping on a pile of books"
        style="max-width: 400px"
      />
      <p style="font-weight: 500; text-align: center; font-size: 1.5rem; line-height: 2rem;">Please enable JavaScript to view MangaDex.</p>
    </div>
</noscript>
    `);
  });
});
```

</details>

**Comment by lupus78** [comment]
I've updated to 2.7.1 and the headers are okay. No undefined of Invalid Date values.
```
$ curl -I -XGET localhost:3000/api/search/autocomplete
HTTP/1.1 200 OK
access-control-allow-origin: *
last-modified: Fri, 27 Oct 2023 09:27:22 GMT
etag: W/"UzMBhPAyL6"
cache-control: stale-while-revalidate
content-type: application/json
date: Fri, 27 Oct 2023 09:27:22 GMT
connection: close
content-length: 841
```

I set the Route rules in nuxt.config.ts's roputeRules main config, not under nitro.routeRules
like so:
```js
export default defineNuxtConfig({
  ...
  nitro: {
    routeRules: {
      // "/api/property": { headers: { 'cache-control': 'public, max-age=600' } },
      // '/api/search/autocomplete': { headers: { 'cache-control': 'public, max-age=600' } }
    },
    compressPublicAssets: true,
    prerender: {
      // crawlLinks: true,
      routes: ['/sitemap.xml']
    }
  },

  routeRules: {
    '/': { prerender: true },
    '/api/availability/**': { swr: 600 },
    '/api/search/autocomplete': { swr: true }
  },
  ...
```

Btw, it's confusing to have routeRules and nitro.routeRules, those are the same?

**Comment by pi0** [comment]
Dear @ Tristan971 Could you send me a reproducible environment? I have spent time creating a new fresh project to confirm it now works. I understand that something is wrong on your side but you are expecting me to blindly resolve your issue (for free) without any more information. That's not possible... So please if you expect any followup provide more info or reach me out for a private demo.

<img width="1029" alt="image" src="https://github.com/unjs/nitro/assets/5158436/b8c9a832-5ad4-4ea6-8b27-b530048cd2ed">
 
Also thanks for heads up about lower case header. I'm aware and this check is actually intentional to support headers via direct fetch which used to not normalized.

----

Thanks for confirming dear @lupus78! Yes they are aliases, for Nuxt, you might directly use top-level `routeRules`.

**Comment by ManasMadrecha** [comment]
@pi0 I wanted to send you a demo project, and even created a new project, but fortunately or unfortunately 😁 in the new project, there's no such error. 

😳 but in my existing main project, even though I deleted the nuxt folder, and even reinstalled the Nuxt and Nitropack, I still get the undefined error in both dev and production. I thought it must be some misconfiguration in my project, but then even others are getting this error and also until last week, I didn't have any cache issues. Also, one thing I am using is dayjs in every api route, and also I have named every cached route manually, i.e., `name` key, but I don't know how it might be causing the issue. Because even in the brand new demo app, I had named the test api cached route, and there was no error.

While for the time being, I have used the plugin hack mentioned at the top of this thread (I even removed etag res header in the hook), and now the app is functioning, and even getting Cache hit in subsequent requests due to Firebase. So this issue is not breaking my project at the moment.

I'll try to come up with a reproduction with a new project with trial and error though. Many appreciation and best wishes to you for for prompt responses and efforts 🙏🏻😊

**Comment by ManasMadrecha** [comment]
@lupus78 I got an Invalid Date in a last modified header in a simple cached router which is only returning just a text.

**Comment by ManasMadrecha** [comment]
@pi0 I had not deleted the node_modules folder. Now did that, and reinstalled everything and no undefined error in the main project. 😁🙏🏻 so now no need for that plugin hack as well.

**Comment by mcrapts** [comment]
In case anyone reads this, I fixed it by first removing the node_modules folder and package-lock.json, and then running `npm install`.
