### ISSUE TITLE
When `static` is set to `true` page is not prerendered and endpoint not ejected

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#1875]
### Environment

stackblitz starter

### Reproduction

https://stackblitz.com/edit/github-vfbafb?file=nitro.config.ts

Run npm run build and take a look at .output/public, there is nothing.

### Describe the bug

When using the key static, I expect that data are prerendered and the endpoint ejected from the final build (because there is content in the public directory).

**Comment by Barbapapazes** [comment]
Maybe, I should try to add prerender but not working with /**

**Comment by Barbapapazes** [comment]
You can take a look at this PR: https://github.com/unjs/website/pull/182

Every page prerendered is also a file in the raw folder. Since this content is already in /public, I do know if this is something we want.

**Comment by pi0** [comment]
The `static: true` flag is an internal flag to specify the build is **full static** and has no server. Nuxt for example internally uses it you probably don't need to specify it manually.

---

There are 3 possible ways for a route to be pre-rendered:

- It is explicitly defined in `prender.routes` array as a valid route (not wildcard but any path you can open in your browser)
- It is declared in prerendering stage using `x-nitro-prerender` header
- It can be discovered by the crawler when discovering a new route

Using `prerender: true` in the route rules, is only a shortcut to define in `prerender.routes` array. Wildcard routes make no sense because they cannot be fetched any how.

Also consider that Nuxt, by default pushes `/` and all predictable pages routes to the `prerender.routes` array and enables crawler so if a link is visible in any of these pages, crawler continues to discover them.
