### ISSUE TITLE
Netlify Forms with Nuxt3

### ISSUE THREAD

**Issue by dbzx10299** [unjs/nitro#2013]
### Describe the feature

There is a problem using forms with netlify because it only works if the netlify build command is `npm run generate`. The problem is when `npm run generate` is used, then the regular serverless functions stop working (not the edge functions). For the serverless functions to work, `npm run build` has to be used as the netlify build command.

I tried using a route rule and setting the netlify build command to `npm run build`, but this does not work. This piece of code prerenders the contact page as expected, and the netlify functions work, but netlify is not able to pick up on the form.

```js
defineNuxtConfig({
  routeRules: {
    '/contact': { prerender: true }
  }
})
```

This is creating a problem because getting access to forms causes the serverless functions to no longer work due to the build command having to be `npm run generate` and using `npm run build `in order to use serverless functions causes the form not to work. The edge functions work either way with `npm run build` or  `npm run generate`.

Edge functions are nice but we might still need to leverage serverless functions though since they use a node js runtime whereas edge functions use a deno runtime.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by cesarbhering** [comment]
Hi, did you found a solution for this? I'm stuck in the same problem.

**Comment by pi0** [comment]
You need to use `build` command always to leverage from server-side functionalities. (generate 

Your usage of route rules seems about to be right. But in order to investigate further, please make a minimal reproduction. Since your question is related to Nuxt, please consider opening it in [Nuxt Disussions](https://github.com/nuxt/nuxt/discussions) and feel free to ping me everywhere  👍🏼
