### ISSUE TITLE
Hiding x-powered-by by default

### ISSUE THREAD

**Issue by GalacticHypernova** [unjs/nitro#2156]
### Describe the feature

The `x-powered-by` header provides no functional purpose besides provide unnecessary information to the client, which could indirectly lead to more targetted attacks, as it provides malicious actors an idea of which vulnerabilities to look for based on the technology of the host. It is a security standard to omit this header and is heavily recommended by all the major web entities, including OWASP and MDN.

[MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers#x-powered-by):
![image](https://github.com/unjs/nitro/assets/92037085/d44f310a-1d0f-4620-aba5-015ad35b268d)

[OWASP](https://cheatsheetseries.owasp.org/cheatsheets/HTTP_Headers_Cheat_Sheet.html#x-powered-by):
![image](https://github.com/unjs/nitro/assets/92037085/c48ad176-6b54-408f-80ea-0b710700318c)

@Baroshem had already implemented this in [Nuxt Security](https://github.com/Baroshem/nuxt-security), and I believe this should be a framework level handler as opposed to a higher level abstraction like a module or a plugin, especially considering those who use Nitro as a standalone. 
Sending x-powered-by is an anti-pattern, and I think adding this anti-pattern detection will benefit all included.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
1. Nitro currently **DOES NOT** add this header so this issue is not even relevant to nitro today.
2. Nitro might add this header by default in the future with similar ways to disable
3. Nuxt particularly has this header **as a feature** + an option to opt out. And Nuxt is not alone super popular Express and many other web servers do it by default
4. When there are so many obvious ways to detect technologies (Nuxt is at least super easily and deliberately detectable) this attempt does not solve **anything** or adds **zero** value unless you can give a solution to hide ALL MEANS of Nuxt detection
5. Even if in theory you can (completely) hide technology somehow, it is called "security through security".

---

You also hide information in your screenshot.

<img width="619" alt="image" src="https://github.com/unjs/nitro/assets/5158436/18a395cd-d07a-4f09-ab1b-0fe726d5b5ef">
