### ISSUE TITLE
Allow libraries to use `#imports`

### ISSUE THREAD

**Issue by huang-julien** [unjs/nitro#2294]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    2.9.3
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/unjs-nitro-starter-ty3v72?file=server%2Fplugins%2Fappinsights.ts,nitro.config.ts,package.json&title=Nitro%20Starter

### Describe the bug

Don't really know if it's more of a feature or a bug. 

Currently some libraries provide plugins or files that uses `#imports` (in the case of `nitro-applicationinsights`, it imports `useRuntimeConfig`).
 it seems that it doesn't go trhough any transformation.

I think we don't have this issue on Nuxt because of the import-transform plugin.

**Comment by pi0** [comment]
Hi. As you mentioned in [docs](https://github.com/huang-julien/nitro-applicationinsights?tab=readme-ov-file#%EF%B8%8F-change-your-nitro-configuration), external imports from `node_modules` need to be in `externals/inline`.

I'm not sure it is a feasible idea to transform all files from node_modules by default and I guess things work with Nuxt setups because by default Nuxt modules are included to be transformed. 

We can do the same with Nitro modules (feel free to make a new issue for this), but I guess first you need to (and I highly recommend too) `nitro-applicationinsights` into a Nitro module
