### ISSUE TITLE
ERR_MODULE_NOT_FOUND when inlining some modules

### ISSUE THREAD

**Issue by huang-julien** [unjs/nitro#2308]
### Environment

------------------------------
- Operating System: Windows_NT
- Node Version:     v20.10.0
- Nuxt Version:     -
- CLI Version:      3.11.1
- Nitro Version:    2.9.3
- Package Manager:  pnpm@8.14.1
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/unjs-nitro-starter-mhus1e?file=module%2Fmod.ts,module%2Fruntime%2Fplugin.ts,nitro.config.ts&title=Nitro%20Starter

### Describe the bug

There's currently an issue (again sorry :pray:) with applicationinsights node.

We have a different issue on stackblitz and windows.

On windows we have 
![315223782-3fba0b2a-3488-4761-bf25-8c048a30cf0e](https://github.com/unjs/nitro/assets/63512348/11ae96ef-5c8f-4e62-9d00-087988cc34b8)

while on stackblitz the module is not found.

The only way to fix it seems to be to force the resolution of mlly to 1.4.0.

I think it's probably due the strip comment feature for mlly `hasEsmSyntax` and `hasCjsSyntax` is behind an experimental feature flag not enabled by default.

### Additional context

The issue with windows is that the absolute paths generated in `.nitro/dev/index.mjs` are generated without `file://` for applicationinsights imports. 
![image](https://github.com/unjs/nitro/assets/63512348/c3c6dc72-0d7b-4a3c-badb-a6e4db82fc6f)

After manually adding them back 
![image](https://github.com/unjs/nitro/assets/63512348/b1e1e866-bb02-4d39-b111-14da6092c611)

We have another issue which is the stackblitz one.

**Comment by huang-julien** [comment]
here's the ouput with mlly 1.4.0 
```ts
import * as ApplicationInsights from 'file://G:/repo/nitro/node_modules/.pnpm/applicationinsights@2.9.5/node_modules/applicationinsights/out/applicationinsights.js';
import ApplicationInsights__default, { DistributedTracingModes } from 'file://G:/repo/nitro/node_modules/.pnpm/applicationinsights@2.9.5/node_modules/applicationinsights/out/applicationinsights.js';

```

**Comment by pi0** [comment]
We probably cannot safely enable stripping comments for mlly until next major version that uses AST-aware stripping.

I know it is a pain for some legacy modules but making changes to CJS/ESM detection that can fixes one legacy module can break other legacy modules. 

I am closing this issue because the only common reported case is applicationinsights but if there are more common legacy packages that having issues, i would be happy to see what we can do for Nitro v2 fix.


Made a tracker issue in https://github.com/huang-julien/nitro-applicationinsights/issues/59 for an alternative suggestion.
