### ISSUE TITLE
Nuxt/Nitro: legacyExternals 2+x faster than default node-externals in prod build

### ISSUE THREAD

**Issue by pawelgur** [unjs/nitro#2369]
### Environment

Rather big Nuxt 3 SSR application with over 50 nuxt modules, tens of pages, tens of components (many async), majority imported from multiple npm dependencies. Nuxt build generates around 800 .mjs files.
nuxt@3.10.3, nitropack@2.9.6, rollup@4.14.1

### Reproduction

Unfortunately repo is private and it will be very time consuming to recreate dummy app with similar amount of files and deps, hopefully info below will be useful enough.

### Describe the bug

Our Nuxt SSR app prod build `Building Nuxt Nitro server (preset: node-server)` step runs for ~6min on Linux machine and ~17min on Windows machine (with quick fix from https://github.com/unjs/nitro/issues/2367 applied).

Using [legacyExternals](https://nitro.unjs.io/config#legacyexternals) brings build time down to 2min for both platforms.

Seems like there's a performance issue in default [node-externals plugin](https://github.com/unjs/nitro/blob/main/src/rollup/plugins/externals.ts#L83) (especially on Windows).

**Comment by pawelgur** [comment]
At this point we have no choice other than using `legacyExternals`. Unfortunately there's little documentation on this. Is it safe to use?

**Comment by pi0** [comment]
Hi, dear @pawelgur. It might be due to bundling a full build of vue. 

If you can make an issue in the nuxt repo with a simple repository that reproduces the problem, I can happily investigate on my Windows machine and try to move it forward either as a nuxt fix or nitro fix if relevant.

It is rather complex to track the investigation from here without having minimal reproduction, i hope you can relate.

**Comment by pi0** [comment]
Thanks. I understand that changing the switch makes an overall difference and good to know the proposed change improves perf on windows (there is a draft for #2371)

There might be different other factors for speed difference. legacy externals does does not include many improvements and bug fixes that are covered with externals.

Also since there might be different causes to this, i would suggest if you like to have another tracker, use an issue in Nuxt repo.
