### ISSUE TITLE
Docs: explain index files for server routing

### ISSUE THREAD

**Issue by geromegrignon** [unjs/nitro#2415]
### Describe the feature

The [server routes](https://nitro.unjs.io/guide/routing) documentation is missing a basic folder structure scenario, implying you are familiar with file-based routing structure.

It doesn't explain you can prefix files with `index`, like `index.get.ts`.

It unlocks using a folder for crud operations like:

```
articles
  - index.get.ts
  - index.post.ts
  - index.delete.ts
```

Or being able to cover routes like `/articles` and `/articles/upcoming`.

```
articles
  index.get.ts
  upcoming
    index.get.ts
```

      

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
PR more than welcome to improve nitro docs 🙏🏼

**Comment by geromegrignon** [comment]
Awesome I wanted to wait for feedback from the team before starting working on it. I'll land a PR!

**Comment by ilyafish** [comment]
@geromegrignon please a PR would be huge for this!

Using your example, I had my routes configured like this:

```
src/api/v1
  - articles.get.ts
  - articles.post.ts
  - articles.delete.ts
src/api/v1/articles
  - upcoming.get.ts
  - upcoming.post.ts
```

It drove me crazy because I couldn't find any examples of doing this any other way while having a feeling it was possible and I was missing something. I only found this because my OCD finally had enough and I decided to spend an hour going through nearly every issue until I came across this.

**Comment by geromegrignon** [comment]
Hi @ilyafish, sure I'll work on it tomorrow! Glad it already helped!
