### ISSUE TITLE
Why is ioredis a dependency?

### ISSUE THREAD

**Issue by boehs** [unjs/nitro#2462]
ioredis is a peer dependency of unstorage, but it is a dependency of nitro despite it not being used. The docs of unstorage say you should install ioredis if you want redis in unstorage, and I agree with them. Seems to have been introduced in #2266, but I'm honestly not sure why.

I personally think it would be better to not burden the 99% of people not using redis with this, especially as

1. no other unstorage dependencies get preferential treatment like this
2. people who need it can run one command and be happy forever
3. a majority of people couldn't use this even if they wanted because a majority of nitro targets are likely serverless

**Comment by pi0** [comment]
Hi.  ioredis (sadly) had been always being installed through `nitro > unstorage` as a dependency for a long time. we removed it from unstorage to make the situation better but since there are already production users who were assuming it is installed (reported in https://github.com/unjs/nitro/issues/2265) as a mitigation effort we basically _moved_ dep to nitro.

I'm not happy it is there (and lots of more transitional unused sub-dependencies and extra files) but until Nitro v3, we have to sadly keep it there.
