### ISSUE TITLE
Augment the config types for modules options

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/nitro#2685]
### Describe the feature

Hello,

Like in Nuxt, it could be a nice addition to automatically to augment the `NuxtConfig` type to have autocompletion in config from modules.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Please see https://github.com/unjs/nitro/pull/2686#issuecomment-2305906629, and consider using dicussions for ideas before moving forward to PRs 🙏🏼 

I am closing this discussion too because extending dependency on auto generated types and modules are both not in a close roadmap (Nitro as standalone framework is yet evolving)
