### ISSUE TITLE
reduce dependency size

### ISSUE THREAD

**Issue by SuperchupuDev** [unjs/nitro#2739]
### Describe the feature

a few potential improvements i've noticed:

`chokidar` v3 -> v4 (it drops all 13 subdependencies but one)
`fs-extra` -> normal modern `node:fs` usage
`globby` -> `tinyglobby`

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for the suggestions.

Next version of nitro v2 will drop fs-extra because we didn't need it that much (https://github.com/unjs/nitro/pull/2743)

Changing glob lib is tricky and needs more consideration before we adopt something lighter across unjs ecosystem, most likely happening in nitro v3 same for chokiar since watchOptions was exposed to users, it is a breaking change to upgrade but easy one for nitro v3.
