### ISSUE TITLE
Unable to pick a custom port for dev mode, yet code exists to do so

### ISSUE THREAD

**Issue by sasial-dev** [unjs/nitro#306]
### Environment

Nitropack: `0.4.8`
Node: `16.11.0`

### Reproduction

N/A

### Describe the bug

As shown at https://github.com/unjs/nitro/blob/main/src/cli.ts#L22 - there is the code avaliable to allow users to pick a custom port/configure the dev server further.

### Additional context

We need to pick a port to allow use to debug our serverside while using our frontend on port :3000.
We have a specific port we need to pin it on, but we can't.

**Comment by sasial-dev** [comment]
As a workaround, we've liturally got a .js script with:
```js
import { createDevServer, createNitro, build, prepare } from 'nitropack'

const nitro = await createNitro({
    dev: true,
    preset: 'nitro-dev'
})
const server = createDevServer(nitro)
await server.listen(50451)
await prepare(nitro)
await build(nitro)
```

**Comment by danielroe** [comment]
Have you tried setting the PORT environment variable?

**Comment by sasial-dev** [comment]
Yep, with no luck
We even tried adding it to doppler (our secrets manager that injects into the env)

**Comment by sasial-dev** [comment]
<img width="285" alt="Code-RWP30DAS" src="https://user-images.githubusercontent.com/44125644/174952718-cb1a6cd4-f8c0-4090-a55f-da7e074a5076.png">

**Comment by itpropro** [comment]
Any news on this @danielroe ? `NITRO_PORT` doesn't work for me in dev, but `PORT` does work. `PORT` is already used for many other things and we want to keep dev analogue to prod, where we use `NITRO_PORT`.

**Comment by michaelkplai** [comment]
Looking at the [commit history](https://github.com/unjs/nitro/commits/main/src/cli/commands/dev.ts) for `src/cli/commands/dev.ts`:

- After v2.3.1, port couldn't be specified when using the `nitropack dev` command since the [port options weren't passed to the listen call](https://github.com/unjs/nitro/commit/710f9e5ab53eb8f0f5323c8f140327e69e6a7b46#diff-8430eac0f649ae8c33c6f079668ebf8672d503f415ad0f7c2eef7cfc8c2c658d:~:text=await%20server.listen(%7B%7D)%3B).
- v2.6.0, fixes support for using `PORT`. See [commit](https://github.com/unjs/nitro/commit/215bffc650a78df824ab00c77d88352e5b969cfb#:~:text=await%20server.listen(listhenOptions.port%2C%20listhenOptions)%3B).
