### ISSUE TITLE
Support cluster mode for node preset

### ISSUE THREAD

**Issue by pi0** [unjs/nitro#451]
https://github.com/nuxt/framework/pull/7089

It could be via a new `node-cluster` preset.

**Comment by Mastercuber** [comment]
The forked processes can operate in 2 ways:
1. new processes gets forked
2. all forks run in one node application (using [worker_threads](https://nodejs.org/dist/latest-v18.x/docs/api/worker_threads.html))

The memory usage could be compared.
For restarting when a worker die's ("self-healing")  a new process can be forked with `cluster.fork()`.

For [setting up](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clustersettings) the cluster workers the [`setupPrimary`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clustersetupprimarysettings) function can be used:
```es
cluster.setupPrimary({
  exec: './.output/server/index.mjs',
  execArgv: [],
  args: ['--use', 'https'],
  silent: false,
  serialization: 'advanced',
  uid: 1000,
  gid: 1000,
  windowsHide: true,
  inspectPort: 8000,
  cwd: './workers-root/'
});
```
the `exec` file is the server entry. Arguments can be passed to the worker processes with `args`. Instead of `silent: false` also `stdio` could be used to get control of the workers IO in the main process (if this is needed).  When the IO of the forked processes is used, `advanced` as serialization between the processes could be investigated. `windowsHide` hides the normally spawned console window on windows. For debugging the workers `inspectPort` can be used (how to set individual ports). A working directory for the workers can be set with `cwd` (how to set individual working directories and also debug ports if wanted?).

The scheduling Policy  must be set before calling `cluster.setupPrimary()`.

### Worker Object Access
The workers are available in the main process through [`cluster.workers`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clusterworkers) and in the worker processes through [`cluster.worker`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clusterworker) the current worker process can be accessed.

### Handling Events
After the workers are running, a [`disconnect`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#event-disconnect) or `exit` Event Handler can be attached to all workers for handling gracefully exits, disconnects and manual shutdowns. Error handling can be done with the 'error' event. For the purpose of setting up a worker, the [`fork`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#event-fork) Event - on the cluster - or the `online` Event - on [cluster](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#event-online_1) and [worker](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#event-online) - can be used and for setup, after the network port is reachable, the `listening` event can be used on the cluster and on the workers. To react to a call to `cluster.setupPrimary()` the [`setup`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#event-setup) Event can be used on the cluster.

### Shutdown the cluster
To stop the main process [`cluster.disconnect([callback])`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clusterdisconnectcallback) can be called to first shutdown all workers and then finish the main process in the callback function.

### Spawn new workers
More worker processes can be spawned by calling [`cluster.fork([env])`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clusterforkenv).

### IPC
Messages from the main to workers can be send with[ `woker.send()`](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#workersendmessage-sendhandle-options-callback). One way to communicate from the worker to the main, is, to listen for the `message` event on the worker from the main.

**Comment by pi0** [comment]
@Mastercuber If you think it is relavant, we could support more options as environment variables to make cluser mode customizable.

Closing issue as we have an initial support now.

**Comment by Mastercuber** [comment]
For an initial support this seems enough. Each started nuxt app can access it's worker process through `cluster.worker`.

The processes doesn't need to communicate to each other, so IPC is not needed.
A logging tag could be added to the beginning of each log line, to indicate from which worker the info was logged.

Some cluster settings could be "exposed" through `nuxt.config.ts`, but while reading the [docs](https://nodejs.org/dist/latest-v18.x/docs/api/cluster.html#clustersettings) I can't find an option to suggest.

**Comment by Mastercuber** [comment]
When I'm trying to use the preset (`preset: 'nuxt'` in config) with Nuxt **3.0.0-rc.9** Nitro **0.5.2**, the `node-server` preset is used when building the module (shown by `npx nuxi preview`).

**Comment by pi0** [comment]
Have you tried NITRO_PRESET=node-cluster ?

**Comment by Mastercuber** [comment]
No I didn't. With the env var it works :grimacing:.
