### ISSUE TITLE
`static` target support for non-platform targets

### ISSUE THREAD

**Issue by danielroe** [unjs/nitro#603]
e.g. `node-server`

**Note**: Vercel support coming in https://github.com/unjs/nitro/pull/545.

**Comment by gcavanunez** [comment]
Hey guys, was playing with nitro today, and man its awesome! 

While playing around with swr caching option, though it works great, noticed the type defs [`CacheOptions`](https://github.com/unjs/nitro/blob/bdb25df8d62eab7dabdaa455ffeeaf2a3a68775d/src/runtime/cache.ts#L14) only has the `boolean` and not the `boolean | number`. Not sure if this is an entirely different thing to tackle or if due to the coupling between the static support it would be addressed via this issue's resolution.

The source of my confusion from this area:
- section of the docs that just mentions the boolean flag [/introduction/cache](https://nitro.unjs.io/guide/introduction/cache) 
- section of the docs that just mentions the union (boolean | number) [/config#routerules](https://nitro.unjs.io/config#routerules)

**Comment by oneart-dev** [comment]
Would be nice to add this info to docs, 4 hours of my life gone trying understand why swr not working for me. Hope to see node support soon.

**Comment by manniL** [comment]
> Would be nice to add this info to docs, 4 hours of my life gone trying understand why swr not working for me. Hope to see node support soon.

Totally agreed! PR welcome 😋

**Comment by pi0** [comment]
We do support SWR for node out of the box today :) You can enable this by using `routeRules: { '/**': { swr: true }`. This issue is trying to implement ISR/Static (cache permanently until next deploy)

**Comment by alanpoulain** [comment]
Have you changed something recently then? It was not working for me with `routeRules: { "/**": { swr: 1 } }` and `nuxt generate` + `nuxt preview` (Node context).

**Comment by manniL** [comment]
> Have you changed something recently then? It was not working for me with `routeRules: { "/**": { swr: 1 } }` and `nuxt generate` + `nuxt preview` (Node context).

You would need to use `nuxt build` then. `generate` is for pre-rendering **only**.

**Comment by alanpoulain** [comment]
I'm not sure to understand then. In the documentation it says:
> `swr` enables a static build, that lasts for a configurable TTL.

I don't see where the static data are rendered. And fundamentally it should be able to prerender all the pages as well, don't you think?

**Comment by manniL** [comment]
@alanpoulain `swr` means it will render a page on-the-fly and stores the result in a cache. Technically there are two age settings ([docs](https://nitro.unjs.io/guide/introduction/cache#options)).

* `maxAge` - time until the cache result will be sent to the client, if expired, it will do a **full new fetch**
* `staleMaxAge` - time until the cache result will be sent to the client **without revalidating in the background**

In all cases, there is a server needed to serve the requests (on-the-fly or via cache), hence you can't use `generate`.

**Comment by alanpoulain** [comment]
The documentation needs to be modified then: it is not a static build, cache headers are just added to the rendered response, isn't it?

**Comment by manniL** [comment]
> The documentation needs to be modified then: it is not a static build, cache headers are just added to the rendered response, isn't it?

I agree the wording is confusing. But AFAIK it is a bit more than just cache headers. The rendered response itself will be cached on the server and actually returned.
Happy to have @pi0 elaborating more on it though ☺️

**Comment by oneart-dev** [comment]
@pi0 does it mean swr per route not working in node?
```json
routeRules: {
      '/': { swr: 1800, prerender: true },
      '/other-route': { swr: 600 },
}
```
This is not working for me. And I can't use one swr rule for every route as some of them can be cashed for ages and some have to be refreshed every N minutes.

Do we have issue for swr in node support i can track?

**Comment by danielroe** [comment]
It should work in Node. If it isn't, please do open an issue with reproduction.

Note that `swr` and `prerender` are alternatives and can't be both enabled at the same time.

**Comment by oneart-dev** [comment]
@danielroe It does not work sadly. issue created https://github.com/unjs/nitro/issues/905

**Comment by manniL** [comment]
Let's follow up in #905 and keep this issue related to `static` then 😋

**Comment by Bakusedu** [comment]
Thanks guys for your prompt responses. I think i'm also experiencing same issue, i might be wrong, it just feels strange as the guidelines on the documentation on [route rules](https://nuxt.com/docs/guide/concepts/rendering#route-rules) seems not to be working for me. Here is my current implementation test trying to get route rule `static: true` to work.

So, i have a page `new.vue` with this template:
`<script setup></script>
  <template>
	  <div>
		  <h1>New Static Page Test</h1>
		  <h2>{{ new Date() }}</h2>
	  </div>
  </template>
`
.
.
Route rule definition in `nuxt.config.ts`
`routeRules: {
  '/new': { static: true },
  },`
.
.
Testing on vercel deployment:
new.vue on page visit. Note the time 👇 
<img width="494" alt="Screenshot 2023-02-08 at 20 04 27" src="https://user-images.githubusercontent.com/34550806/217627814-9fb5e2c8-f754-4e19-a5b7-3069efb3a510.png">
new.vue on page refresh. Note the time difference 👇 
<img width="510" alt="Screenshot 2023-02-08 at 20 04 40" src="https://user-images.githubusercontent.com/34550806/217628088-b4402c5c-47a9-496b-ba17-7eadeac7331a.png">

Since the routeRules definition for `/new` is static, i feel the time snapshots above should be the same and should only change when the app is deployed again. 

i'm currently using Nuxt 3.1.1

**Comment by valernyx** [comment]
Is there any update or more information on support for AWS Lambda + CloudFront?  

I've been trying to get hybrid rendering working for our app deployed to Lambda for the better part of a month, and I am unclear if this is currently supported or not?  We currently have an SSR app deployed on AWS Lambda and serving static assets (but no static routes) out of S3/CloudFront, but we are now trying to introduce hybrid rendering to render a handful of pages statically, and I am hitting major walls.

I have this config defined in `nuxt.config.ts` (just as a test):

` routeRules: {
    '/:my_test': { static: true },
    '/my-test': { static: true },
  },`

Locally with `npm run build && npm run start` OR `npm run build && nuxi preview` I cannot get the selected routes to render statically - they remain in SSR mode.  When I deploy up to our Lambda, I have the same issue.  The routes defined above are still rendering as SSR.  I've alternatively tried to use `prerender: true` and `swr: true` but I get the same result there as well.  I've stared at this docs page for hours but I feel like I am missing something: https://nuxt.com/docs/guide/concepts/rendering/#coming-in-nuxt-3.

From what I've read above it sounds like other platforms outside of Netlify and Vercel should support this... but perhaps not?

Thanks for any help or guidance anyone can provide 🙏

**Comment by mathijsfr** [comment]
Are routeRules supported for a normal kubernetes setup in digitalocean? Having ssr: false and ssr: true on some routes doesn't seem to work for me.

**Comment by pi0** [comment]
There is a `static` preset available for non-platform targets.

If you have any issues or questions regarding usage of route rules (for hybrid ssr+static) feel free to use Discussions tab 👍🏼
