### ISSUE TITLE
Set a default Cache-Control for public static assets

### ISSUE THREAD

**Issue by nathanchase** [unjs/nitro#762]
### Describe the feature

For all public static assets, we can define a best practice value for the Cache-Control header, to fall in line with the Google Lighthouse scoring of [serving assets with an efficient cache policy](https://developer.chrome.com/en/docs/lighthouse/performance/uses-long-cache-ttl/).

`Cache-Control: max-age=31536000, immutable`

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. This is possible since Nitro 2.1 to specify `maxAge` for `publicAssets`. Since we are not sure if public assets are properly hashed or not, nitro has no default value but Nuxt sets it for `_nuxt`/buildDir  https://github.com/nuxt/nuxt/blob/f225ebd6435d1d9305d1d143f835ea921798a2ba/packages/nuxt/src/core/nitro.ts#L89
