### ISSUE TITLE
Plugins being called twice on startup (dev)

### ISSUE THREAD

**Issue by mwohlan** [unjs/nitro#766]
### Environment

See stackblitz reproduction

### Reproduction

https://stackblitz.com/edit/github-cesuxd?file=nitro.config.ts,plugins%2Ftest.ts

### Describe the bug

Plugins are being run twice on startup. Is this behaviour as expected since there is not much documentation on nitro plugins and their behaviour ?

**Comment by manniL** [comment]
Yes, because it will be automatically registered by just putting the file in the `plugins` folder and you add it "manually" again there.

Example only with auto-registering: https://stackblitz.com/edit/unjsnitroissues766?file=nitro.config.ts,plugins%2Ftest.ts

This could be improved in the docs I'd say

**Comment by pi0** [comment]
(PR welcome to improve docs)

**Comment by pi0** [comment]
Currently triage and cleaning up stalled issues and honestly it is more an edge case we might be able to simply fix in nitro ~> https://github.com/unjs/nitro/issues/2450
