### ISSUE TITLE
Empty headers in cachedEventHandler

### ISSUE THREAD

**Issue by Darkside73** [unjs/nitro#783]
### Environment

Node 16, nitro latest

### Reproduction

api/foo.get.ts

```ts
export default cachedEventHandler((event) => {
  console.log(event.node.req.headers) // prints '{}'
  console.log(getHeaders(event)) // prints '{}'

  return {
    foo: 'bar'
  }
})
```

### Describe the bug

When using `cachedEventHandler` the request headers return an empty object. It works as expected when using `eventHandler`

**Comment by johankrijt** [comment]
I have the same issue, which seems to originate from these lines: https://github.com/unjs/nitro/blob/681751237cfc6b23d0989132322399c200915071/src/runtime/cache.ts#L206-L207

**Comment by trc-mathieu** [comment]
@Darkside73 Any idea if this is a bug? Would you happen to know the reason behind not passing the original headers to the proxy request?

**Comment by johankrijt** [comment]
It's to prevent unintentional caching of user specific data (and expose this data to a different user when the response is created from the cache). For this same reason the body of the request is also cleared.

**Comment by Darkside73** [comment]
@trc-mathieu Unfortunately, I have no idea.  I've created my own implementation of cached handler

Here is a simplified example
```ts
// server/utils/createCachedEndpoint.ts

const config = useRuntimeConfig()

export default function (remoteUrl: string) {
  return eventHandler(async () => {
    const cacheDisabled = config.cacheDisabled
    const cacheKey = 'cache_' + remoteUrl

    let data
    if (!cacheDisabled) {
      data = await useStorage().getItem(`redis:${cacheKey}`)
    }

    if (!data) {
      const response = await fetch(remoteUrl)
      if (response.ok) {
        data = await response.json()
        if (!cacheDisabled) {
          useStorage().setItem(`redis:${cacheKey}`, data)
        }
      } else {
        throw createError({
          statusCode: response.status,
          statusMessage: response.statusText
        })
      }
    }
    return data
  })
}
```

**Comment by trc-mathieu** [comment]
ok, I'm trying to understand the use case of `createCachedHandler` then. If the wrapped handler doesn't have access to the body nor the headers, we can only use it I guess with a get request and query params? My use case is that the first call to the wrapped handler needs access to the body and the header in order to properly cache the result. i.e. I need to extract the user token from the header, execute the wrapped handler while being authenticated and then cache the result for the same user. Would it be possible to have this optional? By default, you could enforce that body and headers are not passed, but I see a use case where it would be nice to use. As options, we could have something like 
```javascript
export default cachedEventHandler((event) => {
 
   return callSomethingThatRequiresAuth(getHeadears(event)['token'])
 
},{
   name:'my-authenticated-user-cache',
   getKey:(event)=>getHeaders(event)['token'],
   withProxyHeaders: true,
   withProxyBody: true
})
```
Thanks!

**Comment by Hebilicious** [comment]
@Darkside73 could you please provide a reproduction ?

**Comment by pi0** [comment]
Hi. This is intentional behavior. headers are removed in a cached event handler as it is supposed to be shared between requests. (similar: https://github.com/unjs/nitro/issues/1238#issuecomment-1547974264) You can use cachedFunction to partially cache some part of logic and still access headers. 

We plan to support `varies` option also to allow some safe headers.

**Comment by Darkside73** [comment]
@Hebilicious minimal reproduction https://github.com/Darkside73/empty-headers-in-cached-event-handler
