### ISSUE TITLE
.nitroignore support

### ISSUE THREAD

**Issue by motea927** [unjs/nitro#843]
### Describe the feature

Sometimes, we need to ignore some public folder's file (not all files) in production,
But currently only [noPublicDir](https://github.com/unjs/nitro/blob/7ba7eaff803deaad80094735ace95837c847c60b/src/build.ts) option,
I use Nuxt hooks `close` to remove some file after the build,
But it may very slow when use `compressPublicAssets`,
Because it need copy -> compress -> remove,
Hope can adding ignore some public folder's file option.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We could support something similar to nuxt ignore option for nitro.

**Comment by asbermudez** [comment]
I am struggling with this issue, but for different reason. The current behavior does not allow you to have .spec files in the same folder as middleware/routes because they get bundled automatically and they break. 
Having a .nuxtignore-like (.nitroignore?) option would be great, as keeping the spec files separated does not allow a quick overview of which files are untested.
