### ISSUE TITLE
`$fetch.create` is not inheriting types

### ISSUE THREAD

**Issue by ElYaiko** [unjs/nitro#932]
### Environment

- Operating System: `Darwin`
- Node Version:     `v16.14.0`
- Nuxt Version:     `3.1.2`
- Nitro Version:    `2.1.2`
- Package Manager:  `npm@8.18.0`
- Builder:          `vite`
- User Config:      `app`, `runtimeConfig`, `css`, `build`, `modules`, `vite`, `experimental`, `nitro`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `()`
- Build Modules:    `-`

### Reproduction

-

### Describe the bug

Type for $fetch.create is not using the `NitroFetchOptions` instead, is causing problem in Nuxt with the `method` prop:
https://github.com/unjs/nitro/blob/f7eed65069f02904a58b7c97f2da55c55c39d4f5/src/types/fetch.ts#L94

**Comment by ElYaiko** [comment]
Any update please? is causing lots problem when using a interceptor with $fetch.create, like it cannot resolve the promise type of a Nuxt/api route

**Comment by Hebilicious** [comment]
@ElYaiko Could you please provide a reproduction ? 🙏

**Comment by ElYaiko** [comment]
> @ElYaiko Could you please provide a reproduction ? 🙏

https://stackblitz.com/edit/github-yn4nmm?file=plugins%2Ftest.ts,package.json
Related https://github.com/nuxt/nuxt/issues/20287

**Comment by pi0** [comment]
You can use generic to set the types for custom fetch instances to be same (and Nuxt I guess is already handling it properly). 

It is probably not right approach to inherit types of `$fetch` to a custom instance of `$fetch.create()` because setting a base URL, can change the types actually.

In case you belive types could be improved feel free to open an issue in `ofetch` repo directly 🙏🏼
